mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
mustHave(alice,dogLicense).
