set_random(seed(100)).
solve('METHINKS IT IS LIKE A WEASEL').
evolution(1,26,'ECXZYUACMSOWRWVLLHEEXKYNVAHU').
evolution(2,25,'ECXHYUACMSOWRWVLLHEEXKYNBADU').
evolution(3,24,'ECXHYUACGSOWRWVLLHEEXKYNBSDU').
evolution(4,23,'ECXHYNACGSOXRWVLLPEEXKYNBSDU').
evolution(5,22,'ECXHYNACGSOXRWVLLPEEAKYNBSDU').
evolution(6,21,'ECNHYNKCGSOXRWVLLAEEAKYNBSDU').
evolution(7,20,'ECNHYNKSGSOXRWVLLAEEAKYNBSDU').
evolution(8,19,'ECNHYNKSGIOXRWVLLAEEAKYNBSDU').
evolution(9,18,'DCNHYNKSGIOXRWVLLAEEAKWNBSDU').
evolution(10,17,'DCNHYNKSGIOXRWVLIGEEAKWNBSDU').
evolution(11,16,'DCNHYNKSGIOXRWVLIGEEAKWEBSDU').
evolution(12,15,'DENHYNKSGIOXRWVLIGEEAKWEBSDU').
evolution(13,15,'DENHDNKSGIOXRWVLIGEEAKWEBSDU').
evolution(14,15,' ENHFNKSGIOXRWVLIGEEAKWEBSDU').
evolution(15,14,' ENHINKSGIOXRWVLIGEEAKWEBSDU').
evolution(16,14,' EEHINKSGIOXRWVLIGEEAKWEBSDU').
evolution(17,14,' EEHINKSGI XRWVLIGEEAKWEBSDU').
evolution(18,13,' EEHINKSGI XRWVLIGE AKWEBSDU').
evolution(19,12,' EEHINKSGI XRWULIGE AKWEASDU').
evolution(20,11,' EEHINKSGITXRWULIGE AKWEASDU').
evolution(21,10,' EEHINKSGITXRWULIKE AKWEASDU').
evolution(22,10,' EEHINKSGITKRWULIKE AKWEASDU').
evolution(23,10,' ECHINKSGITKRWULIKE AKWEASDU').
evolution(24,10,' ECHINKSDITKRWULIKE AKWEASDU').
evolution(25,10,' ECHINKSDITJRWNLIKE AKWEASDU').
evolution(26,10,' ECHINKSDITERWNLIKE AKWEASDU').
evolution(27,8,' ECHINKSDIT IWNLIKE AKWEASDU').
evolution(28,8,' ECHINKSDIT IDNLIKE AKWEASDU').
evolution(29,7,' ECHINKSDIT IDNLIKE AKWEASDL').
evolution(30,7,' ECHINKSDIT IANLIKE AKWEASDL').
evolution(31,7,' E HINKSDIT IANLIKE AKWEASDL').
evolution(32,6,' E HINKSDIT ISNLIKE AKWEASDL').
evolution(33,6,' E HINKSDIT ISBLIKE AKWEASDL').
evolution(34,6,' E HINKSDIT ISBLIKE AFWEASQL').
evolution(35,5,' E HINKSDIT ISBLIKE A WEASQL').
evolution(36,5,' E HINKSDIT ISBLIKE A WEASNL').
evolution(37,5,' E HINKSDIT ISBLIKE A WEASBL').
evolution(38,5,' E HINKSDIT ISBLIKE A WEASBL').
evolution(39,5,' E HINKSDIT ISBLIKE A WEASBL').
evolution(40,4,' E HINKSDIT ISBLIKE A WEASEL').
evolution(41,4,' E HINKSDIT ISBLIKE A WEASEL').
evolution(42,4,' E HINKSAIT ISBLIKE A WEASEL').
evolution(43,3,' E HINKS IT ISBLIKE A WEASEL').
evolution(44,3,' E HINKS IT ISBLIKE A WEASEL').
evolution(45,3,' E HINKS IT ISBLIKE A WEASEL').
evolution(46,3,' E HINKS IT ISBLIKE A WEASEL').
evolution(47,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(48,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(49,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(50,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(51,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(52,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(53,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(54,2,' ETHINKS IT ISBLIKE A WEASEL').
evolution(55,2,' ETHINKS IT ISALIKE A WEASEL').
evolution(56,2,' ETHINKS IT ISALIKE A WEASEL').
evolution(57,2,' ETHINKS IT ISALIKE A WEASEL').
evolution(58,2,' ETHINKS IT ISALIKE A WEASEL').
evolution(59,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(60,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(61,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(62,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(63,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(64,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(65,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(66,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(67,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(68,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(69,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(70,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(71,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(72,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(73,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(74,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(75,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(76,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(77,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(78,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(79,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(80,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(81,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(82,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(83,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(84,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(85,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(86,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(87,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(88,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(89,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(90,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(91,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(92,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(93,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(94,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(95,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(96,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(97,1,' ETHINKS IT IS LIKE A WEASEL').
evolution(98,0,'METHINKS IT IS LIKE A WEASEL').
