set_random(seed(100)).
solve('METHINKS IT IS LIKE A WEASEL').
set_random(seed(100)).
evolution(1,27,' IUQEPVPMBILDSTPNRHSYXBTYYPQ').
evolution(2,26,' IUHEPVPMBILDSTPNRHSYXBTYYPQ').
evolution(3,25,' GUHEPVPMBILDSTPNRWSYVBVYYPL').
evolution(4,24,' GGHEPVPMBILNSTPNKWSYVBVYYPL').
evolution(5,23,' GGHEPLPMBILNSTLNKWSYVBVYYPL').
evolution(6,22,' EGHEPLPMBILNSTLNKWSYVBVYYPL').
evolution(7,21,' EGHEPLP BILNSTLNKDSYVBVYYPL').
evolution(8,20,' EGHEPLP BILNSTLNKDJYVBVYSPL').
evolution(9,19,' EGHEPLP BILNSTLNKDJYVBEYSPL').
evolution(10,16,' EGHEPLS ITLNSRLNKDJYVBEYSPL').
evolution(11,15,' EGHEPLS ITLISRLNKDJYVBEYSPL').
evolution(12,15,' EGHEPDS ITLISRLNKDJYVBEYSPL').
evolution(13,14,' EGHEPDS ITLISRLNKD YVBEYSPL').
evolution(14,13,' EGHXPDS ITLISRLNKD AVBEYSPL').
evolution(15,13,' EAHXPDS ITLISRLNKD AVBEYSPL').
evolution(16,13,' EAHCPDS ITLISRLNKD AVBEYSPL').
evolution(17,12,' EAHCRDS ITLISRLIKD AVBEMSPL').
evolution(18,12,' EAHCHDS ITLISRLIKD AVBEMSPL').
evolution(19,11,'MEAHCHDS ITLISRLIKD AIBEMSVL').
evolution(20,10,'MEWBCHKS ITLISRLIKD AIBEASVL').
evolution(21,10,'MELBCHKS ITLISRLIKD AIBEASVL').
evolution(22,9,'MELBCNKS ITLISRLIKD AIBEASVL').
evolution(23,9,'MELBCNKS ITLISDLIKD AIBEASVL').
evolution(24,9,'MELB NKS ITLISDLIKD AIBEASVL').
evolution(25,9,'MEIB NKS ITLISDLIKD AIBEASVL').
evolution(26,9,'MEIB NKS ITAISDLIKD AIBEASVL').
evolution(27,9,'MEFB NKS ITAISDLIKD AIBEASVL').
evolution(28,8,'MEFB NKS ITAISDLIKD AIWEASVL').
evolution(29,8,'MEFB NKS ITAISDLIKD AIWEASVL').
evolution(30,7,'MEFBINKS ITAISDLIKD ANWEASVL').
evolution(31,7,'MEFBINKS ITAISDLIKA ANWEASVL').
evolution(32,7,'MEFBINKS ITAISDLIKA AGWEASVL').
evolution(33,7,'MEFBINKS ITAISDLIKA AGWEASVL').
evolution(34,7,'MEFBINKS ITAISDLIKA AGWEASVL').
evolution(35,7,'MEFBINKS ITAISDLIKA ADWEASVL').
evolution(36,7,'MEFBINKS ITAISDLIKA ADWEASPL').
evolution(37,7,'MEFBINKS ITAISDLIKA ADWEASCL').
evolution(38,7,'MEFBINKS ITAISDLIKA ADWEASCL').
evolution(39,7,'MEFBINKS ITAISDLIKA ADWEASCL').
evolution(40,7,'MEFBINKS IT ISDLIKA ADWEASCK').
evolution(41,7,'MEFAINKS IT ISDLIKA ADWEASCK').
evolution(42,6,'METAINKS IT ISDLIKA ADWEASCK').
evolution(43,6,'MET INKS IT ISDLIKA ADWEASCK').
evolution(44,6,'MET INKS IT ISDLIKA ABWEASCK').
evolution(45,6,'MET INKS IT ISDLIKA ABWEASCK').
evolution(46,6,'MET INKS IT ISBLIKA ABWEASCK').
evolution(47,6,'MET INKS IT ISBLIKA ABWEASCK').
evolution(48,6,'MET INKS IT ISBLIKA ABWEASCA').
evolution(49,5,'MET INKS IT IS LIKA ABWEASCA').
evolution(50,5,'MET INKS IT IS LIKA ABWEASCA').
evolution(51,5,'MET INKS IT IS LIKA ABWEASCA').
evolution(52,5,'MET INKS IT IS LIKA ABWEASCA').
evolution(53,5,'MET INKS IT IS LIKA ABWEASCA').
evolution(54,5,'MET INKS IT IS LIKA ABWEASBA').
evolution(55,5,'MET INKS IT IS LIK  ABWEASBA').
evolution(56,5,'MET INKS IT IS LIK  ABWEASBA').
evolution(57,5,'MET INKS IT IS LIK  ABWEASBA').
evolution(58,5,'MET INKS IT IS LIK  ABWEASBA').
evolution(59,5,'MET INKS IT IS LIK  ABWEASBA').
evolution(60,4,'METHINKS IT IS LIK  ABWEASBA').
evolution(61,4,'METHINKS IT IS LIK  AAWEASBA').
evolution(62,4,'METHINKS IT IS LIK  AAWEASBA').
evolution(63,4,'BETHINKS IT IS LIK  AAWEASBL').
evolution(64,4,'BETHINKS IT IS LIK  AAWEAS L').
evolution(65,4,'BETHINKS IT IS LIK  AAWEAS L').
evolution(66,4,'BETHINKS IT IS LIK  AAWEAS L').
evolution(67,4,'BETHINKS IT IS LIK  AAWEAS L').
evolution(68,4,'BETHINKS IT IS LIK  AAWEAS L').
evolution(69,4,'BETHINKS IT IS LIK  AAWEAS L').
evolution(70,4,'AETHINKS IT IS LIK  AAWEAS L').
evolution(71,4,'AETHINKS IT IS LIK  AAWEAS L').
evolution(72,4,'AETHINKS IT IS LIK  AAWEAS L').
evolution(73,3,'HETHINKS IT IS LIKE AAWEAS L').
evolution(74,2,'HETHINKS IT IS LIKE A WEAS L').
evolution(75,2,'HETHINKS IT IS LIKE A WEAS L').
evolution(76,2,'HETHINKS IT IS LIKE A WEAS L').
evolution(77,2,'HETHINKS IT IS LIKE A WEAS L').
evolution(78,1,'METHINKS IT IS LIKE A WEAS L').
evolution(79,1,'METHINKS IT IS LIKE A WEAS L').
evolution(80,0,'METHINKS IT IS LIKE A WEASEL').
solve('METHINKS IT IS LIKE A WEASEL').
