#!/bin/bash

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
NORMAL="\033[0;39m"

OK=0
DIFF=0
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
mkdir -p "$root/output-eyeprolog"

echo -e "${YELLOW}-------------------------------------------------${NORMAL}"
echo -e "${YELLOW}running the eyelet examples and test cases${NORMAL}"
eyeprolog_version=$(${EYEPROLOG:-eyeprolog} --version 2>&1 | head -1)
echo -e "${YELLOW}using eyelet with ${eyeprolog_version}${NORMAL}"
echo -e "${YELLOW}-------------------------------------------------${NORMAL}"
echo ""

pad () {
    [ "$#" -gt 1 ]
    [ -n "$2" ]
    printf "%$2.${2#-}s" "$1"
}

begin=$(date +%s)
for file in "$root"/input/*.pl
do
    f="$(basename "$file")"
    echo -en "$(pad "${f}" -36)"
    start=$(($(date +%s%N)/1000000))
    if "$root/eyelet-eyeprolog" "$file" > "$root/output-eyeprolog/${f}"; then
        status=0
    else
        status=$?
    fi
    end=$(($(date +%s%N)/1000000))
    echo -en "${YELLOW}$(pad "$((end - start)) ms" 10)${NORMAL} "

    if [[ $status -le 2 ]] && git diff --quiet -- "output-eyeprolog/${f}"; then
        match=1
    else
        match=0
    fi
    if [[ $match -eq 1 ]]; then
        echo -e "${GREEN}OK${NORMAL}"
        ((OK++))
    else
        echo -e "${RED}DIFF${NORMAL}"
        ((DIFF++))
    fi
done
end=$(date +%s)
echo ""

echo -e "${YELLOW}$((end - begin)) s${NORMAL} ${GREEN}${OK} OK${NORMAL} ${RED}${DIFF} DIFF${NORMAL}"
if [[ ${DIFF} -eq 0 ]]; then
    exit 0
else
    exit 2
fi
