set_random(seed(100)).
solve('METHINKS IT IS LIKE A WEASEL').
set_random(seed(100)).
evolution(1, 27, 'KHMFAFFWBNXLDAJEGMEQVVDJYCMN').
evolution(2, 26, 'KEMFAFFWBNXLDAJEGMEQVVDJYCMN').
evolution(3, 25, 'KEMFANFWBNXLDAJEGMEQVVDJYCMN').
evolution(4, 24, 'KEMFANFWBNPLDAJEGIEQVVAJYCEN').
evolution(5, 23, 'KEMFANFWBNPADSJEGIEQVVAJYCEN').
evolution(6, 22, 'KEMFANFSBNPADSJEGIEQVVAJYCEN').
evolution(7, 22, 'BEMFANFSBNPADSJETIEQVVAJYPEN').
evolution(8, 21, 'BEMFANFSPNPADS ETIEQOVAJYPEN').
evolution(9, 20, 'BEMFANFSPNPADS ETIEQOVWBYPEN').
evolution(10, 19, 'BEMFANFSPNPADS ETIEQO WBYPEN').
evolution(11, 18, 'BEMFANFSPNPADS ETIEQO WBAPEN').
evolution(12, 17, 'BEMFANFSPFPADS LTIEQO WBAPEN').
evolution(13, 16, 'BEMFANFSPFPADS LTIEQO WEAPEN').
evolution(14, 16, 'BEEFANFSPFPADS LTIEQO WEAPEN').
evolution(15, 15, 'BEEFANFSPFPADS LZIEQA WEAPEN').
evolution(16, 14, 'BEEFINFSPFZADS LZFEQA WEAPEN').
evolution(17, 13, 'BEEFINFSPFZADS LIBEFA WEAPEN').
evolution(18, 12, 'AEEFINKSPFZADS LIBEFA WEAPEN').
evolution(19, 12, 'AEEFINKSPFMADS LIBEFA WEAPEU').
evolution(20, 11, 'AEEFINKS FMADS LIBEFA WEAPEU').
evolution(21, 10, 'MEEFINKS FMADS LIBEFA WEAPEU').
evolution(22, 10, 'MEBFINKS FMADS LIBEFA WEAPEU').
evolution(23, 10, 'MEBDINKS FUADS LIBEFA WEAPEU').
evolution(24, 10, 'MEBDINKS FKADS LIBEFA WEAPEU').
evolution(25, 10, 'MEBDINKS FKADS LI EFA WEAPEU').
evolution(26, 10, 'MEBDINKS FIADS LI EFA WEAPEU').
evolution(27, 10, 'MEBDINKS FHVDS LI EYA WEAPEH').
evolution(28, 10, 'MEBCINKS FHVDS LI EYA WEAPEH').
evolution(29, 10, 'MEBCINKS CHVDS LI EYA WEAPEH').
evolution(30, 9, 'MEBCINKS CHVIS LI EYA WEAPEH').
evolution(31, 9, 'MEBCINKS CDVIS LI EYA WEAPEH').
evolution(32, 8, 'MEBCINKS YDVIS LIKEYA WEAPEH').
evolution(33, 7, 'MEBYINKS YTVIS LIKEYA WEAPEH').
evolution(34, 7, 'MEBYINKS YTVIS LIKEKA WEAPEH').
evolution(35, 6, 'MEBYINKS YTVIS LIKEKA WEASEH').
evolution(36, 5, 'MEBYINKS ITVIS LIKEKA WEASEH').
evolution(37, 4, 'MEBHINKS ITVIS LIKEKA WEASEH').
evolution(38, 4, 'MEBHINKS ITVIS LIKEKA WEASEH').
evolution(39, 4, 'MEBHINKS ITCIS LIKEKA WEASEH').
evolution(40, 4, 'MEBHINKS ITCIS LIKEKA WEASEG').
evolution(41, 4, 'MEBHINKS ITCIS LIKEKA WEASEG').
evolution(42, 3, 'METHINKS ITCIS LIKEKA WEASEG').
evolution(43, 3, 'METHINKS ITCIS LIKECA WEASEG').
evolution(44, 3, 'METHINKS ITCIS LIKECA WEASEG').
evolution(45, 2, 'METHINKS ITCIS LIKE A WEASEG').
evolution(46, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(47, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(48, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(49, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(50, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(51, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(52, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(53, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(54, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(55, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(56, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(57, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(58, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(59, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(60, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(61, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(62, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(63, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(64, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(65, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(66, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(67, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(68, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(69, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(70, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(71, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(72, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(73, 1, 'METHINKS ITCIS LIKE A WEASEL').
evolution(74, 1, 'METHINKS ITBIS LIKE A WEASEL').
evolution(75, 1, 'METHINKS ITBIS LIKE A WEASEL').
evolution(76, 1, 'METHINKS ITBIS LIKE A WEASEL').
evolution(77, 1, 'METHINKS ITBIS LIKE A WEASEL').
evolution(78, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(79, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(80, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(81, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(82, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(83, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(84, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(85, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(86, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(87, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(88, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(89, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(90, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(91, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(92, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(93, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(94, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(95, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(96, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(97, 1, 'METHINKS ITAIS LIKE A WEASEL').
evolution(98, 0, 'METHINKS IT IS LIKE A WEASEL').
solve('METHINKS IT IS LIKE A WEASEL').
