set_random(seed(100)).
solve('METHINKS IT IS LIKE A WEASEL').
set_random(seed(100)).
evolution(1,25,'PPWVASWA CLVSSQUC DQMZNRATPT').
evolution(2,24,'PPWHASWA CLVSSQUCUDQMZNRATPT').
evolution(3,24,'GPWHASWA CLVSSQUCUDQMZNRAPPT').
evolution(4,22,'GETHASWA CKVSSQUCUDQMZNRAPPT').
evolution(5,21,'GETHASWA AKVSSQUCUDQMZNRAPPL').
evolution(6,20,'EETHASYA AKVSSQUIUSQMZNRAPPL').
evolution(7,18,'EETHASYS AKVSSQUIFSQMZNRAPEL').
evolution(8,17,'EETHANYS AKVSSQUIFSQMZNRAPEL').
evolution(9,16,'EETHANYS AKJSSQUIFSQM NRAPEL').
evolution(10,16,'EETHANES AKJSSQUIFSQM NRAPEL').
evolution(11,16,'BETHANES AKJSSQZIFSQM HRAPEL').
evolution(12,15,'BETHANXS AKJSSQZIFSQM HRASEL').
evolution(13,14,'BETHANXS AKJSSQZIFEQH HRASEL').
evolution(14,13,'BETHANXS AKJSSQZIFEQA HRASEL').
evolution(15,13,'BETHANES AKJSSQZIFEQA HTASEL').
evolution(16,13,'BETHANES ADJSSQZIFEQA HTASEL').
evolution(17,13,'BETHANES ADJNSQZIFEQA HTASEL').
evolution(18,13,'BETHANES ADENSQZICEQA HTASEL').
evolution(19,13,'BETHANES ACENSQZIYEQA HTASEL').
evolution(20,13,'BETHANBS AUENSQZIYEQA TTASEL').
evolution(21,12,'BETHANBS AUEISQZIYEQA TTASEL').
evolution(22,11,'BETHANBS AUEISQZIKEQA TTASEL').
evolution(23,11,'BETHANBS AUEISDZIKEQA TTASEL').
evolution(24,10,'BETHANBS AUEISDZIKE A TTASEL').
evolution(25,10,'BETHANBS ABEISDZIKE A TTASEL').
evolution(26,9,'BETHANBS ABEISDZIKE A TEASEL').
evolution(27,9,'BETHANBS ABEISDAIKE A TEASEL').
evolution(28,9,'BETHANBS ABEISDAIKE A TEASEL').
evolution(29,9,'BETHANBS ABEISD IKE A TEASEL').
evolution(30,9,' ETHANBS ABEISD IKE A TEASEL').
evolution(31,9,'  THANBS ATEISD IKE A LEASEL').
evolution(32,9,'  THANBS ATEISD IKE A LEASEL').
evolution(33,8,'  THANBS ATEISD IKE A WEASEL').
evolution(34,8,'  THANBS ATEISD IKE A WEASEL').
evolution(35,8,'  THANBS ATEISD IKE A WEASEL').
evolution(36,7,' ETHANBS ATWISD IKE A WEASEL').
evolution(37,7,' ETHANBS ATSISD IKE A WEASEL').
evolution(38,6,' ETHINBS ATSISD IKE A WEASEL').
evolution(39,5,' ETHINBS ATSIS  IKE A WEASEL').
evolution(40,5,' ETHINBS ATSIS  IKE A WEASEL').
evolution(41,5,' ETHINBS ATSIS  IKE A WEASEL').
evolution(42,5,' ETHINBS ATHIS  IKE A WEASEL').
evolution(43,5,' ETHINBS ATAIS  IKE A WEASEL').
evolution(44,5,' ETHINBS  TAIS  IKE A WEASEL').
evolution(45,5,' ETHINBS  TAIS  IKE A WEASEL').
evolution(46,4,' ETHINBS ITAIS  IKE A WEASEL').
evolution(47,4,' ETHINBS ITAIS  IKE A WEASEL').
evolution(48,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(49,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(50,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(51,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(52,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(53,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(54,3,' ETHINBS ITAIS LIKE A WEASEL').
evolution(55,3,' ETFINKS ITAIS LIKE A WEASEL').
evolution(56,3,' ETFINKS ITAIS LIKE A WEASEL').
evolution(57,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(58,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(59,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(60,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(61,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(62,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(63,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(64,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(65,2,'METFINKS ITAIS LIKE A WEASEL').
evolution(66,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(67,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(68,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(69,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(70,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(71,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(72,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(73,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(74,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(75,1,'METHINKS ITAIS LIKE A WEASEL').
evolution(76,0,'METHINKS IT IS LIKE A WEASEL').
solve('METHINKS IT IS LIKE A WEASEL').
