path(angers,nantes).
path(lemans,nantes).
path(angers,nantes).
path(lemans,nantes).
path(chartres,nantes).
path(paris,nantes).
path(angers,nantes).
path(lemans,nantes).
path(chartres,nantes).
path(paris,nantes).
