set_random(seed(100)).
solve('METHINKS IT IS LIKE A WEASEL').
evolution(1,26,' MDDQYMFHITAFYEDQMPQRWYHDDLU').
evolution(2,26,' AJDQYMFHITAFYEDQMPQRWYHDDLU').
evolution(3,25,' AJDQYMFHITAFSODQMPQRWYHDDLU').
evolution(4,23,' AJDQYMFHITAFSODQKPQAWYHDDLU').
evolution(5,21,' ATDQYMF ITAFSODQKPQAWYHDDLU').
evolution(6,20,' ATDQYMF ITAFSODQKPQAWWHDDLU').
evolution(7,19,' ATDQYMF ITAFSODQKPQAWWEDDJU').
evolution(8,18,' ATDQYMF ITAFSODQKPQAWWEDSCU').
evolution(9,17,' ATDQYMF ITAFSODQKEQAWWEDSCU').
evolution(10,16,' ETDQYMF ITAFSODQKEQAWWEDSCC').
evolution(11,15,' ETHQYMF ITAFSODQKEJAWWEDSCC').
evolution(12,14,' ETHQYKF ITAFSODQKEJAWWEDSCC').
evolution(13,13,' ETHQYKF ITAFSPLQKEJAWWEDSCC').
evolution(14,13,' ETHFYKF ITAFSPLQKEJAWWEDSCC').
evolution(15,12,' ETHFYKF ITAFSPLQKEJAWWEDSCL').
evolution(16,12,' ETHFGKF ITAFSPLQKEJAWWEDSCL').
evolution(17,12,' ETHFGKF ITAFSPLAKEJAWWEDSCL').
evolution(18,11,' ETHFGKF ITAFSPLIKEJAWWEDSCL').
evolution(19,10,' ETHFGKC ITAFSPLIKEJAWWEASCL').
evolution(20,10,' ETHFGKC ITAFSMLIKEJAWWEASCL').
evolution(21,9,' ETHFFKC ITAISMLIKEJAWWEASCL').
evolution(22,9,' ETHFFK  ITAISMLIKEJAWWEASCL').
evolution(23,9,' ETHFFK  ITAISGLIKEJAWWEASXL').
evolution(24,8,' ETHFFKS ITAISGLIKEJAGWEASXL').
evolution(25,8,' ETHFFKS ITAISFLIKEJAGWEASXL').
evolution(26,7,' ETHFNKS ITAISFLIKEJAGWEASXL').
evolution(27,6,' ETHFNKS ITAISFLIKE AGWEASXL').
evolution(28,5,' ETHFNKS ITAISHLIKE AGWEASEL').
evolution(29,5,' ETHFNKS ITAISHLIKE AGWEASEL').
evolution(30,5,' ETHFNKS ITAISHLIKE AGWEASEL').
evolution(31,5,' ETHFNKS ITAISHLIKE ACWEASEL').
evolution(32,4,' ETHFNKS IT ISHLIKE ACWEASEL').
evolution(33,4,' ETHFNKS IT ISHLIKE ACWEASEL').
evolution(34,4,' ETHFNKS IT ISHLIKE ACWEASEL').
evolution(35,4,' ETHFNKS IT ISHLIKE ACWEASEL').
evolution(36,4,' ETHFNKS IT ISHLIKE ACWEASEL').
evolution(37,4,' ETHFNKS IT ISHLIKE ABWEASEL').
evolution(38,4,' ETHFNKS IT ISHLIKE ABWEASEL').
evolution(39,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(40,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(41,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(42,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(43,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(44,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(45,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(46,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(47,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(48,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(49,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(50,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(51,4,' ETHFNKS IT ISALIKE ABWEASEL').
evolution(52,4,' ETHANKS IT ISALIKE ABWEASEL').
evolution(53,4,' ETHANKS IT ISALIKE ABWEASEL').
evolution(54,4,' ETHANKS IT ISALIKE ABWEASEL').
evolution(55,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(56,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(57,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(58,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(59,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(60,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(61,4,' ETHANKS IT ISALIKE AAWEASEL').
evolution(62,4,' ETHAMKS IT ISALIKE A WEASEL').
evolution(63,4,' ETHAMKS IT ISALIKE A WEASEL').
evolution(64,4,' ETHAMKS IT ISALIKE A WEASEL').
evolution(65,4,' ETHABKS IT ISALIKE A WEASEL').
evolution(66,4,' ETHABKS IT ISALIKE A WEASEL').
evolution(67,3,' ETHIBKS IT ISALIKE A WEASEL').
evolution(68,3,' ETHIBKS IT ISALIKE A WEASEL').
evolution(69,3,' ETHIBKS IT ISALIKE A WEASEL').
evolution(70,3,' ETHIBKS IT ISALIKE A WEASEL').
evolution(71,3,' ETHIBKS IT ISALIKE A WEASEL').
evolution(72,3,' ETHIBKS IT ISALIKE A WEASEL').
evolution(73,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(74,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(75,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(76,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(77,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(78,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(79,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(80,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(81,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(82,3,' ETHI KS IT ISALIKE A WEASEL').
evolution(83,2,'METHI KS IT ISALIKE A WEASEL').
evolution(84,2,'METHI KS IT ISALIKE A WEASEL').
evolution(85,2,'METHI KS IT ISALIKE A WEASEL').
evolution(86,2,'METHI KS IT ISALIKE A WEASEL').
evolution(87,2,'METHI KS IT ISALIKE A WEASEL').
evolution(88,2,'METHI KS IT ISALIKE A WEASEL').
evolution(89,2,'METHI KS IT ISALIKE A WEASEL').
evolution(90,2,'METHI KS IT ISALIKE A WEASEL').
evolution(91,2,'METHI KS IT ISALIKE A WEASEL').
evolution(92,2,'METHI KS IT ISALIKE A WEASEL').
evolution(93,2,'METHI KS IT ISALIKE A WEASEL').
evolution(94,1,'METHINKS IT ISALIKE A WEASEL').
evolution(95,1,'METHINKS IT ISALIKE A WEASEL').
evolution(96,1,'METHINKS IT ISALIKE A WEASEL').
evolution(97,0,'METHINKS IT IS LIKE A WEASEL').
